/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.HomeWindow;

/**
 *
 * @author Nikhil Rana
 */
public class LeaderboardScrollCard extends javax.swing.JPanel {

    /**
     * Creates new form TeamScrollCard
     */
    public LeaderboardScrollCard() {
        initComponents();
        displayHeading();
    }

    public LeaderboardScrollCard(int rank, String name, int points, int won, int draw, int lost) {
        initComponents();
        this.teamRank = rank;
        this.teamName = name;
        this.teamPoints = points;
        this.matchWon = won;
        this.matchDraw = draw;
        this.matchLost = lost;
        display();
    }

    private void displayHeading() {
        Serial.setText("Rank");
        name.setText("Team Name");
        points.setText("Points");
        won.setText("Won");
        draw.setText("Draw");
        lost.setText("Lost");
    }

    private void display() {
        Serial.setText(String.valueOf(teamRank));
        name.setText(teamName);
        points.setText(String.valueOf(teamPoints));
        won.setText(String.valueOf(matchWon));
        draw.setText(String.valueOf(matchDraw));
        lost.setText(String.valueOf(matchLost));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Serial = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        won = new javax.swing.JLabel();
        draw = new javax.swing.JLabel();
        lost = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(907, 62));

        kGradientPanel1.setBackground(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setkBorderRadius(30);
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 204, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(380, 150));

        Serial.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Serial.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        points.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        points.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        name.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        name.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Serial, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(won, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(draw, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lost)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Serial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(won, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(draw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lost))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private String teamName;
    private int teamPoints;
    private int teamRank;
    private int matchWon;
    private int matchDraw;
    private int matchLost;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Serial;
    private javax.swing.JLabel draw;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lost;
    private javax.swing.JLabel name;
    private javax.swing.JLabel points;
    private javax.swing.JLabel won;
    // End of variables declaration//GEN-END:variables
}
