/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.HomeWindow;

/**
 *
 * @author Nikhil Rana
 */
public class MatchesScrollCard extends javax.swing.JPanel {

    /**
     * Creates new form TeamScrollCard
     */
    private String team1;
    private String team2;
    private int points1;
    private int points2;
    private int diff;

    public MatchesScrollCard(String team1, String team2, int points1, int points2, int diff) {
        initComponents();
        this.team1 = team1;
        this.team2 = team2;
        this.points1 = points1;
        this.points2 = points2;
        this.diff = diff;
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void display()
    {
        Team1.setText(team1);
        Team2.setText(team2);
        team1points.setText(String.valueOf(points1));
        team2points.setText(String.valueOf(points2));
        if (diff >0)
            Result.setText(team1+" won by "+diff+" points");
        else if(diff<0)
            Result.setText(team2+" won by "+ (-1*diff)+" points");
        else 
            Result.setText("Match Draw");
        
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        Vs = new javax.swing.JLabel();
        Points = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        Team2 = new javax.swing.JLabel();
        Team1 = new javax.swing.JLabel();
        team1points = new javax.swing.JLabel();
        team2points = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(380, 150));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBackground(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setkBorderRadius(30);
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(380, 150));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Vs.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Vs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vs.setText("Vs");
        kGradientPanel1.add(Vs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 48, 30));

        Points.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        Points.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Points.setText("Points");
        kGradientPanel1.add(Points, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 90, 19));

        Result.setFont(new java.awt.Font("Ubuntu", 2, 15)); // NOI18N
        Result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Result.setPreferredSize(new java.awt.Dimension(210, 19));
        kGradientPanel1.add(Result, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 260, 30));

        Team2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Team2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kGradientPanel1.add(Team2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 140, 30));

        Team1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Team1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        kGradientPanel1.add(Team1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 30));

        team1points.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        team1points.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        team1points.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(team1points, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, 29));

        team2points.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        team2points.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        team2points.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        kGradientPanel1.add(team2points, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 130, 29));

        add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Points;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel Team1;
    private javax.swing.JLabel Team2;
    private javax.swing.JLabel Vs;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel team1points;
    private javax.swing.JLabel team2points;
    // End of variables declaration//GEN-END:variables
}
