/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AdminWindow;

import Code.Player;
import Code.SameTeamException;
import Code.Team;
import Code.TournamentManagementSystem;
import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Ashish Kumar Singh
 */
public class AddPlayerPanel extends javax.swing.JPanel {

    
    ArrayList<String> AllTeamString;
    /**
     * Creates new form AddTeam
     */
    public AddPlayerPanel() {
        tms = new TournamentManagementSystem();
        refreshTeamString();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        TeamLabel = new javax.swing.JLabel();
        PositionLabel = new javax.swing.JLabel();
        PositionField = new javax.swing.JTextField();
        AddPlayerBtn = new keeptoo.KButton();
        ResetBtn = new keeptoo.KButton();
        TeamNameDropDown = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(122, 207, 131));
        setPreferredSize(new java.awt.Dimension(980, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(254, 254, 254));
        NameLabel.setText("Name");
        add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 250, 40));

        NameField.setBackground(new java.awt.Color(0,0,0,1));
        NameField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        NameField.setForeground(new java.awt.Color(254, 254, 254));
        NameField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(254, 254, 254)));
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });
        add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 390, 40));

        TeamLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        TeamLabel.setForeground(new java.awt.Color(254, 254, 254));
        TeamLabel.setText("Team Name");
        add(TeamLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 250, 40));

        PositionLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        PositionLabel.setForeground(new java.awt.Color(254, 254, 254));
        PositionLabel.setText("Position");
        add(PositionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 250, 40));

        PositionField.setBackground(new java.awt.Color(0,0,0,1));
        PositionField.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        PositionField.setForeground(new java.awt.Color(254, 254, 254));
        PositionField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(254, 254, 254)));
        PositionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PositionFieldActionPerformed(evt);
            }
        });
        add(PositionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 390, 40));

        AddPlayerBtn.setText("Add Player");
        AddPlayerBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        AddPlayerBtn.setkBackGroundColor(new java.awt.Color(198, 171, 229));
        AddPlayerBtn.setkBorderRadius(30);
        AddPlayerBtn.setkEndColor(new java.awt.Color(0, 204, 204));
        AddPlayerBtn.setkFillButton(false);
        AddPlayerBtn.setkHoverEndColor(new java.awt.Color(217, 236, 242));
        AddPlayerBtn.setkHoverForeGround(new java.awt.Color(227, 223, 200));
        AddPlayerBtn.setkHoverStartColor(new java.awt.Color(30, 95, 116));
        AddPlayerBtn.setkStartColor(new java.awt.Color(254, 254, 254));
        AddPlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlayerBtnActionPerformed(evt);
            }
        });
        add(AddPlayerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 160, -1));

        ResetBtn.setText("Reset");
        ResetBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ResetBtn.setkBackGroundColor(new java.awt.Color(0, 204, 51));
        ResetBtn.setkBorderRadius(30);
        ResetBtn.setkEndColor(new java.awt.Color(0, 204, 204));
        ResetBtn.setkHoverEndColor(new java.awt.Color(50, 130, 184));
        ResetBtn.setkHoverForeGround(new java.awt.Color(227, 223, 200));
        ResetBtn.setkHoverStartColor(new java.awt.Color(26, 166, 183));
        ResetBtn.setkStartColor(new java.awt.Color(0, 153, 51));
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 160, -1));

        TeamNameDropDown.setBackground(new java.awt.Color(153, 153, 255, 1));
        TeamNameDropDown.setModel(new DefaultComboBoxModel<>(
            AllTeamString.toArray(
                new String[AllTeamString.size()]
            )
        ));
        TeamNameDropDown.setOpaque(false);
        TeamNameDropDown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TeamNameDropDownItemStateChanged(evt);
            }
        });
        TeamNameDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamNameDropDownActionPerformed(evt);
            }
        });
        add(TeamNameDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 390, 40));
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void reset() {
        NameField.setText("");
        PositionField.setText("");
    }
    
    private void AddPlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlayerBtnActionPerformed
        // TODO add your handling code here:
        String name, team, position;
        name = NameField.getText();
        team = (String) TeamNameDropDown.getSelectedItem();
        position = PositionField.getText();
        Player p = new Player(name,position,team);
        try {
            tms.addNewPlayer(p);
        } catch (SameTeamException ex) {
            
        }
        reset();
    }//GEN-LAST:event_AddPlayerBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFieldActionPerformed

    private void PositionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PositionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PositionFieldActionPerformed

    private void TeamNameDropDownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TeamNameDropDownItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamNameDropDownItemStateChanged

    private void TeamNameDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamNameDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamNameDropDownActionPerformed

    private TournamentManagementSystem tms;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton AddPlayerBtn;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField PositionField;
    private javax.swing.JLabel PositionLabel;
    private keeptoo.KButton ResetBtn;
    private javax.swing.JLabel TeamLabel;
    private javax.swing.JComboBox<String> TeamNameDropDown;
    // End of variables declaration//GEN-END:variables

    void refreshTeamString() {
        ArrayList<Team> allTeams = tms.getAllTeams();
        ListIterator iter = allTeams.listIterator();
        AllTeamString = new ArrayList<>();
        allTeams.forEach(Team -> AllTeamString.add(Team.getTeamName()));
//        allTeams.forEach(Team -> System.out.print(Team.getTeamName()));
        try {
            TeamNameDropDown.setModel(new DefaultComboBoxModel<>(
            AllTeamString.toArray(
                new String[AllTeamString.size()]
            )
        ));
        } catch(NullPointerException e) {
            
        }
    }
}
