/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AdminWindow;

import Code.Team;
import Code.TournamentManagementSystem;

/**
 *
 * @author Ashish Kumar Singh
 */
public class AddTeamPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddTeam
     */
    public AddTeamPanel() {
        tms = new TournamentManagementSystem();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TeamLabel = new javax.swing.JLabel();
        TeamField = new javax.swing.JTextField();
        DescriptionLabel = new javax.swing.JLabel();
        DescriptionField = new javax.swing.JTextField();
        AddTeamBtn = new keeptoo.KButton();
        ResetBtn = new keeptoo.KButton();

        setBackground(new java.awt.Color(222, 128, 118));
        setPreferredSize(new java.awt.Dimension(980, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TeamLabel.setForeground(new java.awt.Color(254, 254, 254));
        TeamLabel.setText("Team Name");
        add(TeamLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 250, 40));

        TeamField.setBackground(new java.awt.Color(0,0,0,1));
        TeamField.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        TeamField.setForeground(new java.awt.Color(254, 254, 254));
        TeamField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(254, 254, 254)));
        TeamField.setOpaque(false);
        TeamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeamFieldActionPerformed(evt);
            }
        });
        add(TeamField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 390, 40));

        DescriptionLabel.setForeground(new java.awt.Color(254, 254, 254));
        DescriptionLabel.setText("Description");
        add(DescriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 250, 40));

        DescriptionField.setBackground(new java.awt.Color(0,0,0,1));
        DescriptionField.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        DescriptionField.setForeground(new java.awt.Color(254, 254, 254));
        DescriptionField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(254, 254, 254)));
        DescriptionField.setOpaque(false);
        DescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionFieldActionPerformed(evt);
            }
        });
        add(DescriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 390, 40));

        AddTeamBtn.setText("Add Team");
        AddTeamBtn.setkBackGroundColor(new java.awt.Color(198, 171, 229));
        AddTeamBtn.setkBorderRadius(30);
        AddTeamBtn.setkEndColor(new java.awt.Color(0, 204, 204));
        AddTeamBtn.setkFillButton(false);
        AddTeamBtn.setkHoverEndColor(new java.awt.Color(217, 236, 242));
        AddTeamBtn.setkHoverForeGround(new java.awt.Color(227, 223, 200));
        AddTeamBtn.setkHoverStartColor(new java.awt.Color(30, 95, 116));
        AddTeamBtn.setkStartColor(new java.awt.Color(254, 254, 254));
        AddTeamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTeamBtnActionPerformed(evt);
            }
        });
        add(AddTeamBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 160, -1));

        ResetBtn.setText("Reset");
        ResetBtn.setkBorderRadius(30);
        ResetBtn.setkEndColor(new java.awt.Color(252, 218, 183));
        ResetBtn.setkHoverEndColor(new java.awt.Color(50, 130, 184));
        ResetBtn.setkHoverForeGround(new java.awt.Color(227, 223, 200));
        ResetBtn.setkHoverStartColor(new java.awt.Color(26, 166, 183));
        ResetBtn.setkStartColor(new java.awt.Color(50, 130, 184));
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 160, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void reset() {
        TeamField.setText("");
        DescriptionField.setText("");
    }
    
    
    private void TeamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeamFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeamFieldActionPerformed

    private void DescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionFieldActionPerformed

    private void AddTeamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTeamBtnActionPerformed
        // TODO add your handling code here:
        String team, description;
        team = TeamField.getText();
        description = DescriptionField.getText();
        Team t = new Team(team, description);
        tms.addNewTeam(t);
        reset();
    }//GEN-LAST:event_AddTeamBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private TournamentManagementSystem tms;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton AddTeamBtn;
    private javax.swing.JTextField DescriptionField;
    private javax.swing.JLabel DescriptionLabel;
    private keeptoo.KButton ResetBtn;
    private javax.swing.JTextField TeamField;
    private javax.swing.JLabel TeamLabel;
    // End of variables declaration//GEN-END:variables
}
